site_name: Kangaroo's Site


theme:
  name: readthedocs
#  language: zh
#  features:
#    - navigation.tabs
#    - navigation.top
#    - search.suggest
#    - search.highlight
plugins:
  - search

nav:
  - Home: index.md
  - About: about.md
  - notes: pdfs.md
  - Poetry: poetry.md
  - Links: links.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
